#http.host: 0.0.0.0
network.host: 0.0.0.0

bootstrap.memory_lock: true

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false
